baseURL = "http://example.com/"
languageCode = "en-us"
title = "AFLIBER"
theme = "minimal"
disqusShortname = "atlasfloraiberica"
googleAnalytics = "UA-192550074-1"
relativeURLS = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown", "_files$", "_cache$"]

[markup.goldmark.renderer]
    unsafe= true

[params]
    author = "Herlander Lima (modified from Calin Tataru Minimal theme)"
    description = "Atlas of the Flora Iberica Database"
    githubUsername = "#"
    accent = "#006600"
    showBorder = true
    backgroundColor = "#f2f2f2"
    font = "Alegreya" # should match the name on Google Fonts!
    # options for highlight.js (version, additional languages, and theme)
    highlight = true
    highlightStyle = "atom-one-light"
    highlightLanguages = ["r"]
    css = ["/css/custom.css"]
    js = ["/js/custom.js"]

    [params.logo]
        url = "logo.png"
        width = 50
        height = 50
        alt = "logo"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    identifier = "about_main"
    url = "/about/"
    name = "About"
    weight = 2

    [[menu.main]]
    identifier = "about_project"
    url = "/about/afliber/"
    name = "AFLIBER database"
    weight = 1
    parent = "about_main"
    
    [[menu.main]]
    identifier = "about_team"
    url = "/about/team/"
    name = "Our team"
    weight = 2
    parent = "about_main"


[[menu.main]]
    url = "/methods/"
    name = "Methods"
    weight = 3

[[menu.main]]
    url = "/updates/"
    name = "Updates"
    weight = 4

[[menu.main]]
    url = "/usage/"
    name = "How to"
    weight = 5

[[menu.main]]
    identifier = "collaborate"
    url = "/collaborate/"
    name = "Collaborate"
    weight = 6

    [[menu.main]]
    identifier = "collab_instructions"
    url = "/collaborate/general_instructions/"
    name = "General Instructions"
    weight = 1
    parent = "collaborate"

    [[menu.main]]
    identifier = "collab_specieslist"
    url = "/collaborate/species_list/"
    name = "- Species List"
    weight = 2
    parent = "collaborate"
    
    [[menu.main]]
    identifier = "collab_distrib"
    url = "/collaborate/species_distrib/"
    name = "- Species Distribution"
    weight = 3
    parent = "collaborate"

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "/mailform/"
    name = "fas fa-lg fa-envelope"
    title = "Contact us"
    weight = 1

[[menu.icon]]
    url = "https://github.com/iramosgutierrez/AFLIBER"
    name = "fab fa-lg fa-github"
    title = "AFLIBER repo"
    weight = 2

[[menu.icon]]
    url = "/download_data/"
    name = "fa fa-lg fa-download"
    title = "Download"
    weight = 3

[permalinks]
    updates = "/updates/:year/:month/:day/:slug/"

