baseURL = "http://example.com/"
languageCode = "en-us"
title = "AFLIBER"
theme = "minimal"
disqusShortname = "afliber-admin" # delete this to disable disqus comments
googleAnalytics = ""
relativeURLS = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown", "_files$", "_cache$"]

[params]
    author = "Herlander Lima (modified from Calin Tataru Minimal theme)"
    description = "Website for AFLIBER (Atlas of the Flora Iberica) database"
    githubUsername = "#"
    accent = "darkgreen"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    # options for highlight.js (version, additional languages, and theme)
    highlight = true
    highlightStyle = "atom-one-light"
    highlightLanguages = ["r"]
    custom_css = ["/css/custom.css"]
    profilePic = "/images/Completeness.png"

    [params.logo]
        url = "logo.png"
        width = 50
        height = 50
        alt = "logo"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

[[menu.main]]
    url = "/usage/"
    name = "How to"
    weight = 5
# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/username/"
    name = "fab fa-github"
    weight = 2

[permalinks]
    post = "/:year/:month/:day/:slug/"

